// apps/react-router-app/app/root.tsx
import {
    Links,
    Meta,
    Outlet,
    Scripts,
    ScrollRestoration,
} from "react-router";
import type { LinksFunction } from "react-router";
import InitialLoadMetrics from "~/components/InitialLoadMetrics";

export const links: LinksFunction = () => [
    { rel: "stylesheet", href: "/shared/global.css" },
];

export function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
            <head>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <Meta />
                <Links />
            </head>
            <body>
                <div className="layout-container">
                    <header className="app-header">
                        <h1 className="app-title">Тестовый стенд</h1>
                        <div className="framework-badge">React Router v7</div>
                        <div className="routing-tech">React Router v7 (Vite, Server Loader + SPA Navigation)</div>
                    </header>
                    {children}
                </div>
                <ScrollRestoration />
                <Scripts />
                <InitialLoadMetrics />
            </body>
        </html>
    );
}

export default function App() {
    return <Outlet />;
}

// apps/qwik-app/src/root.tsx
import { component$ } from '@builder.io/qwik';
import { QwikCityProvider, RouterOutlet } from '@builder.io/qwik-city';
import { InitialLoadMetrics } from './components/InitialLoadMetrics';

export default component$(() => {
    return (
        <QwikCityProvider>
            <head>
                <meta charSet="utf-8" />
                <title>Тестовый стенд — Qwik</title>
                <link rel="stylesheet" href="/shared/global.css" />
            </head>
            <body>
                <div class="layout-container">
                    <header class="app-header">
                        <h1 class="app-title">Тестовый стенд</h1>
                        <div class="framework-badge">Qwik 1.x</div>
                        <div class="routing-tech">QwikCity (Resumability, SPA router)</div>
                    </header>
                    <RouterOutlet />
                </div>
                <InitialLoadMetrics />
            </body>
        </QwikCityProvider>
    );
});
