// apps/qwik-app/src/routes/index.tsx
// Главная страница Qwik SUT.
// Сохраняет nav_t0 = Date.now() в sessionStorage при клике на ссылку.
import { component$ } from '@builder.io/qwik';
import { type DocumentHead, Link, useLocation } from '@builder.io/qwik-city';
import { SUT_ID } from '~/lib/constants';

export default component$(() => {
    const loc = useLocation();
    const sp = loc.url.searchParams;

    const runId = sp.get('run_id') || '';
    const modeId = sp.get('mode_id') || 'manual';
    const iteration = sp.get('iteration') || '1';

    const listParams = new URLSearchParams();
    if (runId) listParams.set('run_id', runId);
    if (modeId) listParams.set('mode_id', modeId);
    if (iteration) listParams.set('iteration', iteration);
    const listHref = `/list?${listParams.toString()}`;

    return (
        <main
            data-test="page-home"
            data-sut-id={SUT_ID}
            data-run-id={runId}
            data-mode-id={modeId}
            data-iteration={iteration}
            class="home-content"
        >
            <h2>Добро пожаловать</h2>
            <p>Тестирование маршрутизации: <strong>{SUT_ID}</strong></p>

            <nav style={{ marginTop: '2rem' }}>
                {/* Qwik <Link> — SPA-навигация через QwikCity router */}
                <Link
                    href={listHref}
                    data-test="link-to-list"
                    class="btn-primary"
                    onClick$={() => {
                        sessionStorage.setItem('nav_t0', String(Date.now()));
                    }}
                >
                    Перейти к списку
                </Link>
            </nav>
        </main>
    );
});

export const head: DocumentHead = {
    title: 'Тестовый стенд — Qwik',
    meta: [{ name: 'description', content: 'SUT qwik_app: тестирование маршрутизации' }],
};

// apps/svelte-app/src/routes/+page.svelte
<script>
    // Главная страница SvelteKit SUT.
    // Сохраняет nav_t0 = Date.now() в sessionStorage при клике на ссылку —
    // список прочитает это значение для вычисления длительности навигации.
    import { page } from '$app/state';

    const SUT_ID = 'svelte_app';

    // Формирование query string для ссылки на /list с параметрами прогона.
    $: searchParams = page.url.searchParams;
    $: listHref = (() => {
        const params = new URLSearchParams();
        const runId = searchParams.get('run_id');
        const modeId = searchParams.get('mode_id');
        const iteration = searchParams.get('iteration');
        if (runId) params.set('run_id', runId);
        if (modeId) params.set('mode_id', modeId);
        if (iteration) params.set('iteration', iteration);
        return `/list?${params.toString()}`;
    })();

    /**
     * Фиксация момента клика для вычисления NAV-метрики.
     * Date.now() сохраняется в sessionStorage, чтобы пережить full-page reload.
     * Для SPA-навигации (SvelteKit) sessionStorage сохраняется в рамках вкладки.
     */
    function handleNavClick() {
        sessionStorage.setItem('nav_t0', String(Date.now()));
    }
</script>

<svelte:head>
    <title>Тестовый стенд — SvelteKit</title>
    <meta name="description" content="SUT {SUT_ID}: тестирование маршрутизации" />
</svelte:head>

<main data-test="page-home" class="home-content">
    <h2>Добро пожаловать</h2>
    <p>Тестирование маршрутизации: <strong>{SUT_ID}</strong></p>

    <nav style="margin-top: 2rem;">
        <!-- SvelteKit <a> перехватывает клик и делает SPA-навигацию -->
        <a
            href={listHref}
            data-test="link-to-list"
            class="btn-primary"
            on:click={handleNavClick}
        >
            Перейти к списку
        </a>
    </nav>
</main>
